/** @format */

import ifsl from "../../assets/blogs/ifsl.jpg";

export const blogData = [
  {
    id: 1,
    image: ifsl,
    title:
      "Cultivating Resilience: The Bomet Integrated Food Security & Livelihood Project’s Transformative Journey",
    date: "1 February 2024",
    summary:
      "Chebunyo ward normally experiences long dry periods that is affecting their farms which is their main source of livelihood. This project seeks to ensure that they have a secure source of livelihood.Victor Cheruiyot, IFSL Project Officer Bomet",
    des1: "We are all striving to create and generate our source of livelihood every day. We wake up to pursue opportunities that ensure a secure future. But in this current age, the certainty we seek is nowhere to be found. Our means of making a living are vulnerable to the changes that our environment faces, especially climate change. This is true for the residents of Chebunyo Ward in Bomet County, whose livelihood has been drastically affected by the ravaging drought that has been rampant across the Horn of Africa. The Integrated Food Security and Livelihood (IFSL) Project is offering hope by providing alternative sources of livelihood. The program covers four main thematic areas: Livelihoods, dedicated to advancing modern farming practices; Water, aimed at enhancing water service coordination and supporting irrigation systems; Environment, fostering environmental conservation to combat climate change; and Cross-cutting issues, addressing challenges related to SGBV.",
    des2: "The Nogriwet Irrigation Scheme was introduced to elevate food production among farmers along the irrigation route, this is accomplished by the construction of a 13.2km water pipeline that directly serves 517 farmers. The beneficiaries were also furnished with a variety of watermelon, cabbage, tomato, and kale seeds. To ensure that there is no overproduction of one produce, the allocation of the seedlings was spread across different blocks. Beyond the irrigation scheme, 50 farmers were provided with 2,500 enhanced Kienyeji Chicks with a survival rate of 94%. Furthermore, they provided two bags of nutrient-rich chicken feeds and essential vaccination services, effectively reducing the poultry mortality rate. The warmer climate of the region has fostered a conducive environment for poultry rearing. Among the beneficiaries, Alice Biomnto and Rutto Kiprono have fully embraced the opportunity and are ready to reap its benefits.",
    des3: "Alice Biomnto heard of the program through the area chief and eagerly became a part of it. She underwent sessions on maintaining and properly taking care of the chicks she received. Armed with the newfound knowledge, she took care of the chicks feeding them with chick and grower mash as they progressed. When the chick feeds ran out, she and her son, Alfred Kirui, found an alternative solution by using her grinding mill to grind a mixture of dried maize, soybeans, and sorghum to sustain them. Once the chicks grow and start laying eggs, they will sell them to her neighbours and provide a stable income for her and her family. This program will benefit not only my family and I, but also my community. For I can sell the newly hatched chicks to my neighbour and encourage them as we move forward.’ She says. Rutto Kipruno struggled with scarcity of water as he tried his hand at farming until he heard of the irrigation scheme in the area. He learnt that the piping system of the irrigation extension line reached his land and excitedly he prepared his land to farm tomatoes. Equipped with a money-maker pump and the tomato seedlings he received, he now pumps water across his farm and is expecting a bountiful harvest that will provide a stable income for his family. In an effort to increase tree coverage within the county and encourage the cultivation of indigenous trees, a total of 25,850 fruit seedlings, including mango, pixie oranges, and lemons, have been distributed to the farmers. The Reformed Cutters Group is one of two groups in the region that have benefited from this initiative focusing on indigenous trees. The group consists of 22 women who have all undergone a transformation from their past involvement in FGM. Their transformation journey began when the chief convened a meeting for all cutters in the area, asking them to stop their former practices and transition to a more sustainable livelihood.",
    author: "IFSL",
  },

  {
    id: 2,
    image: ifsl,
    title:
      "Cultivating Resilience: The Bomet Integrated Food Security & Livelihood Project’s Transformative Journey",
    date: "1 February 2024",
    summary:
      "Chebunyo ward normally experiences long dry periods that is affecting their farms which is their main source of livelihood. This project seeks to ensure that they have a secure source of livelihood.Victor Cheruiyot, IFSL Project Officer Bomet",
    des1: "We are all striving to create and generate our source of livelihood every day. We wake up to pursue opportunities that ensure a secure future. But in this current age, the certainty we seek is nowhere to be found. Our means of making a living are vulnerable to the changes that our environment faces, especially climate change. This is true for the residents of Chebunyo Ward in Bomet County, whose livelihood has been drastically affected by the ravaging drought that has been rampant across the Horn of Africa. The Integrated Food Security and Livelihood (IFSL) Project is offering hope by providing alternative sources of livelihood. The program covers four main thematic areas: Livelihoods, dedicated to advancing modern farming practices; Water, aimed at enhancing water service coordination and supporting irrigation systems; Environment, fostering environmental conservation to combat climate change; and Cross-cutting issues, addressing challenges related to SGBV.",
    des2: "The Nogriwet Irrigation Scheme was introduced to elevate food production among farmers along the irrigation route, this is accomplished by the construction of a 13.2km water pipeline that directly serves 517 farmers. The beneficiaries were also furnished with a variety of watermelon, cabbage, tomato, and kale seeds. To ensure that there is no overproduction of one produce, the allocation of the seedlings was spread across different blocks. Beyond the irrigation scheme, 50 farmers were provided with 2,500 enhanced Kienyeji Chicks with a survival rate of 94%. Furthermore, they provided two bags of nutrient-rich chicken feeds and essential vaccination services, effectively reducing the poultry mortality rate. The warmer climate of the region has fostered a conducive environment for poultry rearing. Among the beneficiaries, Alice Biomnto and Rutto Kiprono have fully embraced the opportunity and are ready to reap its benefits.",
    des3: "Alice Biomnto heard of the program through the area chief and eagerly became a part of it. She underwent sessions on maintaining and properly taking care of the chicks she received. Armed with the newfound knowledge, she took care of the chicks feeding them with chick and grower mash as they progressed. When the chick feeds ran out, she and her son, Alfred Kirui, found an alternative solution by using her grinding mill to grind a mixture of dried maize, soybeans, and sorghum to sustain them. Once the chicks grow and start laying eggs, they will sell them to her neighbours and provide a stable income for her and her family. This program will benefit not only my family and I, but also my community. For I can sell the newly hatched chicks to my neighbour and encourage them as we move forward.’ She says. Rutto Kipruno struggled with scarcity of water as he tried his hand at farming until he heard of the irrigation scheme in the area. He learnt that the piping system of the irrigation extension line reached his land and excitedly he prepared his land to farm tomatoes. Equipped with a money-maker pump and the tomato seedlings he received, he now pumps water across his farm and is expecting a bountiful harvest that will provide a stable income for his family. In an effort to increase tree coverage within the county and encourage the cultivation of indigenous trees, a total of 25,850 fruit seedlings, including mango, pixie oranges, and lemons, have been distributed to the farmers. The Reformed Cutters Group is one of two groups in the region that have benefited from this initiative focusing on indigenous trees. The group consists of 22 women who have all undergone a transformation from their past involvement in FGM. Their transformation journey began when the chief convened a meeting for all cutters in the area, asking them to stop their former practices and transition to a more sustainable livelihood.",
    author: "IFSL",
  },

  {
    id: 3,
    image: ifsl,
    title:
      "Cultivating Resilience: The Bomet Integrated Food Security & Livelihood Project’s Transformative Journey",
    date: "1 February 2024",
    summary:
      "Chebunyo ward normally experiences long dry periods that is affecting their farms which is their main source of livelihood. This project seeks to ensure that they have a secure source of livelihood.Victor Cheruiyot, IFSL Project Officer Bomet",
    des1: "We are all striving to create and generate our source of livelihood every day. We wake up to pursue opportunities that ensure a secure future. But in this current age, the certainty we seek is nowhere to be found. Our means of making a living are vulnerable to the changes that our environment faces, especially climate change. This is true for the residents of Chebunyo Ward in Bomet County, whose livelihood has been drastically affected by the ravaging drought that has been rampant across the Horn of Africa. The Integrated Food Security and Livelihood (IFSL) Project is offering hope by providing alternative sources of livelihood. The program covers four main thematic areas: Livelihoods, dedicated to advancing modern farming practices; Water, aimed at enhancing water service coordination and supporting irrigation systems; Environment, fostering environmental conservation to combat climate change; and Cross-cutting issues, addressing challenges related to SGBV.",
    des2: "The Nogriwet Irrigation Scheme was introduced to elevate food production among farmers along the irrigation route, this is accomplished by the construction of a 13.2km water pipeline that directly serves 517 farmers. The beneficiaries were also furnished with a variety of watermelon, cabbage, tomato, and kale seeds. To ensure that there is no overproduction of one produce, the allocation of the seedlings was spread across different blocks. Beyond the irrigation scheme, 50 farmers were provided with 2,500 enhanced Kienyeji Chicks with a survival rate of 94%. Furthermore, they provided two bags of nutrient-rich chicken feeds and essential vaccination services, effectively reducing the poultry mortality rate. The warmer climate of the region has fostered a conducive environment for poultry rearing. Among the beneficiaries, Alice Biomnto and Rutto Kiprono have fully embraced the opportunity and are ready to reap its benefits.",
    des3: "Alice Biomnto heard of the program through the area chief and eagerly became a part of it. She underwent sessions on maintaining and properly taking care of the chicks she received. Armed with the newfound knowledge, she took care of the chicks feeding them with chick and grower mash as they progressed. When the chick feeds ran out, she and her son, Alfred Kirui, found an alternative solution by using her grinding mill to grind a mixture of dried maize, soybeans, and sorghum to sustain them. Once the chicks grow and start laying eggs, they will sell them to her neighbours and provide a stable income for her and her family. This program will benefit not only my family and I, but also my community. For I can sell the newly hatched chicks to my neighbour and encourage them as we move forward.’ She says. Rutto Kipruno struggled with scarcity of water as he tried his hand at farming until he heard of the irrigation scheme in the area. He learnt that the piping system of the irrigation extension line reached his land and excitedly he prepared his land to farm tomatoes. Equipped with a money-maker pump and the tomato seedlings he received, he now pumps water across his farm and is expecting a bountiful harvest that will provide a stable income for his family. In an effort to increase tree coverage within the county and encourage the cultivation of indigenous trees, a total of 25,850 fruit seedlings, including mango, pixie oranges, and lemons, have been distributed to the farmers. The Reformed Cutters Group is one of two groups in the region that have benefited from this initiative focusing on indigenous trees. The group consists of 22 women who have all undergone a transformation from their past involvement in FGM. Their transformation journey began when the chief convened a meeting for all cutters in the area, asking them to stop their former practices and transition to a more sustainable livelihood.",
    author: "IFSL",
  },
  {
    id: 4,
    image: ifsl,
    title:
      "Cultivating Resilience: The Bomet Integrated Food Security & Livelihood Project’s Transformative Journey",
    date: "1 February 2024",
    summary:
      "Chebunyo ward normally experiences long dry periods that is affecting their farms which is their main source of livelihood. This project seeks to ensure that they have a secure source of livelihood.Victor Cheruiyot, IFSL Project Officer Bomet",
    des1: "We are all striving to create and generate our source of livelihood every day. We wake up to pursue opportunities that ensure a secure future. But in this current age, the certainty we seek is nowhere to be found. Our means of making a living are vulnerable to the changes that our environment faces, especially climate change. This is true for the residents of Chebunyo Ward in Bomet County, whose livelihood has been drastically affected by the ravaging drought that has been rampant across the Horn of Africa. The Integrated Food Security and Livelihood (IFSL) Project is offering hope by providing alternative sources of livelihood. The program covers four main thematic areas: Livelihoods, dedicated to advancing modern farming practices; Water, aimed at enhancing water service coordination and supporting irrigation systems; Environment, fostering environmental conservation to combat climate change; and Cross-cutting issues, addressing challenges related to SGBV.",
    des2: "The Nogriwet Irrigation Scheme was introduced to elevate food production among farmers along the irrigation route, this is accomplished by the construction of a 13.2km water pipeline that directly serves 517 farmers. The beneficiaries were also furnished with a variety of watermelon, cabbage, tomato, and kale seeds. To ensure that there is no overproduction of one produce, the allocation of the seedlings was spread across different blocks. Beyond the irrigation scheme, 50 farmers were provided with 2,500 enhanced Kienyeji Chicks with a survival rate of 94%. Furthermore, they provided two bags of nutrient-rich chicken feeds and essential vaccination services, effectively reducing the poultry mortality rate. The warmer climate of the region has fostered a conducive environment for poultry rearing. Among the beneficiaries, Alice Biomnto and Rutto Kiprono have fully embraced the opportunity and are ready to reap its benefits.",
    des3: "Alice Biomnto heard of the program through the area chief and eagerly became a part of it. She underwent sessions on maintaining and properly taking care of the chicks she received. Armed with the newfound knowledge, she took care of the chicks feeding them with chick and grower mash as they progressed. When the chick feeds ran out, she and her son, Alfred Kirui, found an alternative solution by using her grinding mill to grind a mixture of dried maize, soybeans, and sorghum to sustain them. Once the chicks grow and start laying eggs, they will sell them to her neighbours and provide a stable income for her and her family. This program will benefit not only my family and I, but also my community. For I can sell the newly hatched chicks to my neighbour and encourage them as we move forward.’ She says. Rutto Kipruno struggled with scarcity of water as he tried his hand at farming until he heard of the irrigation scheme in the area. He learnt that the piping system of the irrigation extension line reached his land and excitedly he prepared his land to farm tomatoes. Equipped with a money-maker pump and the tomato seedlings he received, he now pumps water across his farm and is expecting a bountiful harvest that will provide a stable income for his family. In an effort to increase tree coverage within the county and encourage the cultivation of indigenous trees, a total of 25,850 fruit seedlings, including mango, pixie oranges, and lemons, have been distributed to the farmers. The Reformed Cutters Group is one of two groups in the region that have benefited from this initiative focusing on indigenous trees. The group consists of 22 women who have all undergone a transformation from their past involvement in FGM. Their transformation journey began when the chief convened a meeting for all cutters in the area, asking them to stop their former practices and transition to a more sustainable livelihood.",
    author: "IFSL",
  },
  {
    id: 5,
    image: ifsl,
    title:
      "Cultivating Resilience: The Bomet Integrated Food Security & Livelihood Project’s Transformative Journey",
    date: "1 February 2024",
    summary:
      "Chebunyo ward normally experiences long dry periods that is affecting their farms which is their main source of livelihood. This project seeks to ensure that they have a secure source of livelihood.Victor Cheruiyot, IFSL Project Officer Bomet",
    des1: "We are all striving to create and generate our source of livelihood every day. We wake up to pursue opportunities that ensure a secure future. But in this current age, the certainty we seek is nowhere to be found. Our means of making a living are vulnerable to the changes that our environment faces, especially climate change. This is true for the residents of Chebunyo Ward in Bomet County, whose livelihood has been drastically affected by the ravaging drought that has been rampant across the Horn of Africa. The Integrated Food Security and Livelihood (IFSL) Project is offering hope by providing alternative sources of livelihood. The program covers four main thematic areas: Livelihoods, dedicated to advancing modern farming practices; Water, aimed at enhancing water service coordination and supporting irrigation systems; Environment, fostering environmental conservation to combat climate change; and Cross-cutting issues, addressing challenges related to SGBV.",
    des2: "The Nogriwet Irrigation Scheme was introduced to elevate food production among farmers along the irrigation route, this is accomplished by the construction of a 13.2km water pipeline that directly serves 517 farmers. The beneficiaries were also furnished with a variety of watermelon, cabbage, tomato, and kale seeds. To ensure that there is no overproduction of one produce, the allocation of the seedlings was spread across different blocks. Beyond the irrigation scheme, 50 farmers were provided with 2,500 enhanced Kienyeji Chicks with a survival rate of 94%. Furthermore, they provided two bags of nutrient-rich chicken feeds and essential vaccination services, effectively reducing the poultry mortality rate. The warmer climate of the region has fostered a conducive environment for poultry rearing. Among the beneficiaries, Alice Biomnto and Rutto Kiprono have fully embraced the opportunity and are ready to reap its benefits.",
    des3: "Alice Biomnto heard of the program through the area chief and eagerly became a part of it. She underwent sessions on maintaining and properly taking care of the chicks she received. Armed with the newfound knowledge, she took care of the chicks feeding them with chick and grower mash as they progressed. When the chick feeds ran out, she and her son, Alfred Kirui, found an alternative solution by using her grinding mill to grind a mixture of dried maize, soybeans, and sorghum to sustain them. Once the chicks grow and start laying eggs, they will sell them to her neighbours and provide a stable income for her and her family. This program will benefit not only my family and I, but also my community. For I can sell the newly hatched chicks to my neighbour and encourage them as we move forward.’ She says. Rutto Kipruno struggled with scarcity of water as he tried his hand at farming until he heard of the irrigation scheme in the area. He learnt that the piping system of the irrigation extension line reached his land and excitedly he prepared his land to farm tomatoes. Equipped with a money-maker pump and the tomato seedlings he received, he now pumps water across his farm and is expecting a bountiful harvest that will provide a stable income for his family. In an effort to increase tree coverage within the county and encourage the cultivation of indigenous trees, a total of 25,850 fruit seedlings, including mango, pixie oranges, and lemons, have been distributed to the farmers. The Reformed Cutters Group is one of two groups in the region that have benefited from this initiative focusing on indigenous trees. The group consists of 22 women who have all undergone a transformation from their past involvement in FGM. Their transformation journey began when the chief convened a meeting for all cutters in the area, asking them to stop their former practices and transition to a more sustainable livelihood.",
    author: "IFSL",
  },
  {
    id: 6,
    image: ifsl,
    title:
      "Cultivating Resilience: The Bomet Integrated Food Security & Livelihood Project’s Transformative Journey",
    date: "1 February 2024",
    summary:
      "Chebunyo ward normally experiences long dry periods that is affecting their farms which is their main source of livelihood. This project seeks to ensure that they have a secure source of livelihood.Victor Cheruiyot, IFSL Project Officer Bomet",
    des1: "We are all striving to create and generate our source of livelihood every day. We wake up to pursue opportunities that ensure a secure future. But in this current age, the certainty we seek is nowhere to be found. Our means of making a living are vulnerable to the changes that our environment faces, especially climate change. This is true for the residents of Chebunyo Ward in Bomet County, whose livelihood has been drastically affected by the ravaging drought that has been rampant across the Horn of Africa. The Integrated Food Security and Livelihood (IFSL) Project is offering hope by providing alternative sources of livelihood. The program covers four main thematic areas: Livelihoods, dedicated to advancing modern farming practices; Water, aimed at enhancing water service coordination and supporting irrigation systems; Environment, fostering environmental conservation to combat climate change; and Cross-cutting issues, addressing challenges related to SGBV.",
    des2: "The Nogriwet Irrigation Scheme was introduced to elevate food production among farmers along the irrigation route, this is accomplished by the construction of a 13.2km water pipeline that directly serves 517 farmers. The beneficiaries were also furnished with a variety of watermelon, cabbage, tomato, and kale seeds. To ensure that there is no overproduction of one produce, the allocation of the seedlings was spread across different blocks. Beyond the irrigation scheme, 50 farmers were provided with 2,500 enhanced Kienyeji Chicks with a survival rate of 94%. Furthermore, they provided two bags of nutrient-rich chicken feeds and essential vaccination services, effectively reducing the poultry mortality rate. The warmer climate of the region has fostered a conducive environment for poultry rearing. Among the beneficiaries, Alice Biomnto and Rutto Kiprono have fully embraced the opportunity and are ready to reap its benefits.",
    des3: "Alice Biomnto heard of the program through the area chief and eagerly became a part of it. She underwent sessions on maintaining and properly taking care of the chicks she received. Armed with the newfound knowledge, she took care of the chicks feeding them with chick and grower mash as they progressed. When the chick feeds ran out, she and her son, Alfred Kirui, found an alternative solution by using her grinding mill to grind a mixture of dried maize, soybeans, and sorghum to sustain them. Once the chicks grow and start laying eggs, they will sell them to her neighbours and provide a stable income for her and her family. This program will benefit not only my family and I, but also my community. For I can sell the newly hatched chicks to my neighbour and encourage them as we move forward.’ She says. Rutto Kipruno struggled with scarcity of water as he tried his hand at farming until he heard of the irrigation scheme in the area. He learnt that the piping system of the irrigation extension line reached his land and excitedly he prepared his land to farm tomatoes. Equipped with a money-maker pump and the tomato seedlings he received, he now pumps water across his farm and is expecting a bountiful harvest that will provide a stable income for his family. In an effort to increase tree coverage within the county and encourage the cultivation of indigenous trees, a total of 25,850 fruit seedlings, including mango, pixie oranges, and lemons, have been distributed to the farmers. The Reformed Cutters Group is one of two groups in the region that have benefited from this initiative focusing on indigenous trees. The group consists of 22 women who have all undergone a transformation from their past involvement in FGM. Their transformation journey began when the chief convened a meeting for all cutters in the area, asking them to stop their former practices and transition to a more sustainable livelihood.",
    author: "IFSL",
  },
  {
    id: 7,
    image: ifsl,
    title:
      "Cultivating Resilience: The Bomet Integrated Food Security & Livelihood Project’s Transformative Journey",
    date: "1 February 2024",
    summary:
      "Chebunyo ward normally experiences long dry periods that is affecting their farms which is their main source of livelihood. This project seeks to ensure that they have a secure source of livelihood.Victor Cheruiyot, IFSL Project Officer Bomet",
    des1: "We are all striving to create and generate our source of livelihood every day. We wake up to pursue opportunities that ensure a secure future. But in this current age, the certainty we seek is nowhere to be found. Our means of making a living are vulnerable to the changes that our environment faces, especially climate change. This is true for the residents of Chebunyo Ward in Bomet County, whose livelihood has been drastically affected by the ravaging drought that has been rampant across the Horn of Africa. The Integrated Food Security and Livelihood (IFSL) Project is offering hope by providing alternative sources of livelihood. The program covers four main thematic areas: Livelihoods, dedicated to advancing modern farming practices; Water, aimed at enhancing water service coordination and supporting irrigation systems; Environment, fostering environmental conservation to combat climate change; and Cross-cutting issues, addressing challenges related to SGBV.",
    des2: "The Nogriwet Irrigation Scheme was introduced to elevate food production among farmers along the irrigation route, this is accomplished by the construction of a 13.2km water pipeline that directly serves 517 farmers. The beneficiaries were also furnished with a variety of watermelon, cabbage, tomato, and kale seeds. To ensure that there is no overproduction of one produce, the allocation of the seedlings was spread across different blocks. Beyond the irrigation scheme, 50 farmers were provided with 2,500 enhanced Kienyeji Chicks with a survival rate of 94%. Furthermore, they provided two bags of nutrient-rich chicken feeds and essential vaccination services, effectively reducing the poultry mortality rate. The warmer climate of the region has fostered a conducive environment for poultry rearing. Among the beneficiaries, Alice Biomnto and Rutto Kiprono have fully embraced the opportunity and are ready to reap its benefits.",
    des3: "Alice Biomnto heard of the program through the area chief and eagerly became a part of it. She underwent sessions on maintaining and properly taking care of the chicks she received. Armed with the newfound knowledge, she took care of the chicks feeding them with chick and grower mash as they progressed. When the chick feeds ran out, she and her son, Alfred Kirui, found an alternative solution by using her grinding mill to grind a mixture of dried maize, soybeans, and sorghum to sustain them. Once the chicks grow and start laying eggs, they will sell them to her neighbours and provide a stable income for her and her family. This program will benefit not only my family and I, but also my community. For I can sell the newly hatched chicks to my neighbour and encourage them as we move forward.’ She says. Rutto Kipruno struggled with scarcity of water as he tried his hand at farming until he heard of the irrigation scheme in the area. He learnt that the piping system of the irrigation extension line reached his land and excitedly he prepared his land to farm tomatoes. Equipped with a money-maker pump and the tomato seedlings he received, he now pumps water across his farm and is expecting a bountiful harvest that will provide a stable income for his family. In an effort to increase tree coverage within the county and encourage the cultivation of indigenous trees, a total of 25,850 fruit seedlings, including mango, pixie oranges, and lemons, have been distributed to the farmers. The Reformed Cutters Group is one of two groups in the region that have benefited from this initiative focusing on indigenous trees. The group consists of 22 women who have all undergone a transformation from their past involvement in FGM. Their transformation journey began when the chief convened a meeting for all cutters in the area, asking them to stop their former practices and transition to a more sustainable livelihood.",
    author: "IFSL",
  },
  {
    id: 8,
    image: ifsl,
    title:
      "Cultivating Resilience: The Bomet Integrated Food Security & Livelihood Project’s Transformative Journey",
    date: "1 February 2024",
    summary:
      "Chebunyo ward normally experiences long dry periods that is affecting their farms which is their main source of livelihood. This project seeks to ensure that they have a secure source of livelihood.Victor Cheruiyot, IFSL Project Officer Bomet",
    des1: "We are all striving to create and generate our source of livelihood every day. We wake up to pursue opportunities that ensure a secure future. But in this current age, the certainty we seek is nowhere to be found. Our means of making a living are vulnerable to the changes that our environment faces, especially climate change. This is true for the residents of Chebunyo Ward in Bomet County, whose livelihood has been drastically affected by the ravaging drought that has been rampant across the Horn of Africa. The Integrated Food Security and Livelihood (IFSL) Project is offering hope by providing alternative sources of livelihood. The program covers four main thematic areas: Livelihoods, dedicated to advancing modern farming practices; Water, aimed at enhancing water service coordination and supporting irrigation systems; Environment, fostering environmental conservation to combat climate change; and Cross-cutting issues, addressing challenges related to SGBV.",
    des2: "The Nogriwet Irrigation Scheme was introduced to elevate food production among farmers along the irrigation route, this is accomplished by the construction of a 13.2km water pipeline that directly serves 517 farmers. The beneficiaries were also furnished with a variety of watermelon, cabbage, tomato, and kale seeds. To ensure that there is no overproduction of one produce, the allocation of the seedlings was spread across different blocks. Beyond the irrigation scheme, 50 farmers were provided with 2,500 enhanced Kienyeji Chicks with a survival rate of 94%. Furthermore, they provided two bags of nutrient-rich chicken feeds and essential vaccination services, effectively reducing the poultry mortality rate. The warmer climate of the region has fostered a conducive environment for poultry rearing. Among the beneficiaries, Alice Biomnto and Rutto Kiprono have fully embraced the opportunity and are ready to reap its benefits.",
    des3: "Alice Biomnto heard of the program through the area chief and eagerly became a part of it. She underwent sessions on maintaining and properly taking care of the chicks she received. Armed with the newfound knowledge, she took care of the chicks feeding them with chick and grower mash as they progressed. When the chick feeds ran out, she and her son, Alfred Kirui, found an alternative solution by using her grinding mill to grind a mixture of dried maize, soybeans, and sorghum to sustain them. Once the chicks grow and start laying eggs, they will sell them to her neighbours and provide a stable income for her and her family. This program will benefit not only my family and I, but also my community. For I can sell the newly hatched chicks to my neighbour and encourage them as we move forward.’ She says. Rutto Kipruno struggled with scarcity of water as he tried his hand at farming until he heard of the irrigation scheme in the area. He learnt that the piping system of the irrigation extension line reached his land and excitedly he prepared his land to farm tomatoes. Equipped with a money-maker pump and the tomato seedlings he received, he now pumps water across his farm and is expecting a bountiful harvest that will provide a stable income for his family. In an effort to increase tree coverage within the county and encourage the cultivation of indigenous trees, a total of 25,850 fruit seedlings, including mango, pixie oranges, and lemons, have been distributed to the farmers. The Reformed Cutters Group is one of two groups in the region that have benefited from this initiative focusing on indigenous trees. The group consists of 22 women who have all undergone a transformation from their past involvement in FGM. Their transformation journey began when the chief convened a meeting for all cutters in the area, asking them to stop their former practices and transition to a more sustainable livelihood.",
    author: "IFSL",
  },
  {
    id: 9,
    image: ifsl,
    title:
      "Cultivating Resilience: The Bomet Integrated Food Security & Livelihood Project’s Transformative Journey",
    date: "1 February 2024",
    summary:
      "Chebunyo ward normally experiences long dry periods that is affecting their farms which is their main source of livelihood. This project seeks to ensure that they have a secure source of livelihood.Victor Cheruiyot, IFSL Project Officer Bomet",
    des1: "We are all striving to create and generate our source of livelihood every day. We wake up to pursue opportunities that ensure a secure future. But in this current age, the certainty we seek is nowhere to be found. Our means of making a living are vulnerable to the changes that our environment faces, especially climate change. This is true for the residents of Chebunyo Ward in Bomet County, whose livelihood has been drastically affected by the ravaging drought that has been rampant across the Horn of Africa. The Integrated Food Security and Livelihood (IFSL) Project is offering hope by providing alternative sources of livelihood. The program covers four main thematic areas: Livelihoods, dedicated to advancing modern farming practices; Water, aimed at enhancing water service coordination and supporting irrigation systems; Environment, fostering environmental conservation to combat climate change; and Cross-cutting issues, addressing challenges related to SGBV.",
    des2: "The Nogriwet Irrigation Scheme was introduced to elevate food production among farmers along the irrigation route, this is accomplished by the construction of a 13.2km water pipeline that directly serves 517 farmers. The beneficiaries were also furnished with a variety of watermelon, cabbage, tomato, and kale seeds. To ensure that there is no overproduction of one produce, the allocation of the seedlings was spread across different blocks. Beyond the irrigation scheme, 50 farmers were provided with 2,500 enhanced Kienyeji Chicks with a survival rate of 94%. Furthermore, they provided two bags of nutrient-rich chicken feeds and essential vaccination services, effectively reducing the poultry mortality rate. The warmer climate of the region has fostered a conducive environment for poultry rearing. Among the beneficiaries, Alice Biomnto and Rutto Kiprono have fully embraced the opportunity and are ready to reap its benefits.",
    des3: "Alice Biomnto heard of the program through the area chief and eagerly became a part of it. She underwent sessions on maintaining and properly taking care of the chicks she received. Armed with the newfound knowledge, she took care of the chicks feeding them with chick and grower mash as they progressed. When the chick feeds ran out, she and her son, Alfred Kirui, found an alternative solution by using her grinding mill to grind a mixture of dried maize, soybeans, and sorghum to sustain them. Once the chicks grow and start laying eggs, they will sell them to her neighbours and provide a stable income for her and her family. This program will benefit not only my family and I, but also my community. For I can sell the newly hatched chicks to my neighbour and encourage them as we move forward.’ She says. Rutto Kipruno struggled with scarcity of water as he tried his hand at farming until he heard of the irrigation scheme in the area. He learnt that the piping system of the irrigation extension line reached his land and excitedly he prepared his land to farm tomatoes. Equipped with a money-maker pump and the tomato seedlings he received, he now pumps water across his farm and is expecting a bountiful harvest that will provide a stable income for his family. In an effort to increase tree coverage within the county and encourage the cultivation of indigenous trees, a total of 25,850 fruit seedlings, including mango, pixie oranges, and lemons, have been distributed to the farmers. The Reformed Cutters Group is one of two groups in the region that have benefited from this initiative focusing on indigenous trees. The group consists of 22 women who have all undergone a transformation from their past involvement in FGM. Their transformation journey began when the chief convened a meeting for all cutters in the area, asking them to stop their former practices and transition to a more sustainable livelihood.",
    author: "IFSL",
  },
  {
    id: 10,
    image: ifsl,
    title:
      "Cultivating Resilience: The Bomet Integrated Food Security & Livelihood Project’s Transformative Journey",
    date: "1 February 2024",
    summary:
      "Chebunyo ward normally experiences long dry periods that is affecting their farms which is their main source of livelihood. This project seeks to ensure that they have a secure source of livelihood.Victor Cheruiyot, IFSL Project Officer Bomet",
    des1: "We are all striving to create and generate our source of livelihood every day. We wake up to pursue opportunities that ensure a secure future. But in this current age, the certainty we seek is nowhere to be found. Our means of making a living are vulnerable to the changes that our environment faces, especially climate change. This is true for the residents of Chebunyo Ward in Bomet County, whose livelihood has been drastically affected by the ravaging drought that has been rampant across the Horn of Africa. The Integrated Food Security and Livelihood (IFSL) Project is offering hope by providing alternative sources of livelihood. The program covers four main thematic areas: Livelihoods, dedicated to advancing modern farming practices; Water, aimed at enhancing water service coordination and supporting irrigation systems; Environment, fostering environmental conservation to combat climate change; and Cross-cutting issues, addressing challenges related to SGBV.",
    des2: "The Nogriwet Irrigation Scheme was introduced to elevate food production among farmers along the irrigation route, this is accomplished by the construction of a 13.2km water pipeline that directly serves 517 farmers. The beneficiaries were also furnished with a variety of watermelon, cabbage, tomato, and kale seeds. To ensure that there is no overproduction of one produce, the allocation of the seedlings was spread across different blocks. Beyond the irrigation scheme, 50 farmers were provided with 2,500 enhanced Kienyeji Chicks with a survival rate of 94%. Furthermore, they provided two bags of nutrient-rich chicken feeds and essential vaccination services, effectively reducing the poultry mortality rate. The warmer climate of the region has fostered a conducive environment for poultry rearing. Among the beneficiaries, Alice Biomnto and Rutto Kiprono have fully embraced the opportunity and are ready to reap its benefits.",
    des3: "Alice Biomnto heard of the program through the area chief and eagerly became a part of it. She underwent sessions on maintaining and properly taking care of the chicks she received. Armed with the newfound knowledge, she took care of the chicks feeding them with chick and grower mash as they progressed. When the chick feeds ran out, she and her son, Alfred Kirui, found an alternative solution by using her grinding mill to grind a mixture of dried maize, soybeans, and sorghum to sustain them. Once the chicks grow and start laying eggs, they will sell them to her neighbours and provide a stable income for her and her family. This program will benefit not only my family and I, but also my community. For I can sell the newly hatched chicks to my neighbour and encourage them as we move forward.’ She says. Rutto Kipruno struggled with scarcity of water as he tried his hand at farming until he heard of the irrigation scheme in the area. He learnt that the piping system of the irrigation extension line reached his land and excitedly he prepared his land to farm tomatoes. Equipped with a money-maker pump and the tomato seedlings he received, he now pumps water across his farm and is expecting a bountiful harvest that will provide a stable income for his family. In an effort to increase tree coverage within the county and encourage the cultivation of indigenous trees, a total of 25,850 fruit seedlings, including mango, pixie oranges, and lemons, have been distributed to the farmers. The Reformed Cutters Group is one of two groups in the region that have benefited from this initiative focusing on indigenous trees. The group consists of 22 women who have all undergone a transformation from their past involvement in FGM. Their transformation journey began when the chief convened a meeting for all cutters in the area, asking them to stop their former practices and transition to a more sustainable livelihood.",
    author: "IFSL",
  },
];
