import blogImage from '../../assets/blogs/blog.jpg'

export const blogData = [{
        "id": 1,
        "image": blogImage,
        "title": "Beautiful Sunset",
        "date": "1 November 2020",
        "summary": "CEF is a dynamic tech hub that empowers individuals in ourcommunity through coding programs, AI research support, and techforums. We're here to help you learn, connect, and innovate. Join usto be part of a vibrant tech ecosystem, where your journey tosuccess begins. Together, we're shaping the future of technology.",
        "des1": "CEF is a dynamic tech hub that empowers individuals in our community through coding programs, AI research support, and tech forums. We're here to help you learn, connect, and innovate. Join us to be part of a vibrant tech ecosystem, where your journey to success begins. Together, we're shaping the future of technology.",
        "des2": "CEF is a dynamic tech hub that empowers individuals in our community through coding programs, AI research support, and techforums. We're here to help you learn, connect, and innovate. Join usto be part of a vibrant tech ecosystem, where your journey tosuccess begins. Together, we're shaping the future of technology.",
        "des3": "CEF is a dynamic tech hub that empowers individuals in our community through coding programs, AI research support, and tech forums. We're here to help you learn, connect, and innovate. Join us to be part of a vibrant tech ecosystem, where your journey to success begins. Together, we're shaping the future of technology.",
        "author":"Prof John", 
        "eventDate":"2nd April 2019", 
    },

    {
        "id": 2,
        "image": blogImage,
        "title": "Mountain Landscape",
        "date": "1 November 2020",
         "summary": "CEF is a dynamic tech hub that empowers individuals in ourcommunity through coding programs, AI research support, and techforums. We're here to help you learn, connect, and innovate. Join usto be part of a vibrant tech ecosystem, where your journey tosuccess begins. Together, we're shaping the future of technology.",
        "des1": "CEF is a dynamic tech hub that empowers individuals in our community through coding programs, AI research support, and tech forums. We're here to help you learn, connect, and innovate. Join us to be part of a vibrant tech ecosystem, where your journey to success begins. Together, we're shaping the future of technology.",
        "des2": "CEF is a dynamic tech hub that empowers individuals in our community through coding programs, AI research support, and techforums. We're here to help you learn, connect, and innovate. Join usto be part of a vibrant tech ecosystem, where your journey tosuccess begins. Together, we're shaping the future of technology.",
        "des3": "CEF is a dynamic tech hub that empowers individuals in our community through coding programs, AI research support, and tech forums. We're here to help you learn, connect, and innovate. Join us to be part of a vibrant tech ecosystem, where your journey to success begins. Together, we're shaping the future of technology.",
        "author":"Prof John", 
        "eventDate":"2nd April 2019", 
    },

    {
        "id": 3,
        "image": blogImage,
        "title": "City Skyline at Night",
        "date": "1 November 2020",
         "summary": "CEF is a dynamic tech hub that empowers individuals in ourcommunity through coding programs, AI research support, and techforums. We're here to help you learn, connect, and innovate. Join usto be part of a vibrant tech ecosystem, where your journey tosuccess begins. Together, we're shaping the future of technology.",
        "des1": "CEF is a dynamic tech hub that empowers individuals in our community through coding programs, AI research support, and tech forums. We're here to help you learn, connect, and innovate. Join us to be part of a vibrant tech ecosystem, where your journey to success begins. Together, we're shaping the future of technology.",
        "des2": "CEF is a dynamic tech hub that empowers individuals in our community through coding programs, AI research support, and techforums. We're here to help you learn, connect, and innovate. Join usto be part of a vibrant tech ecosystem, where your journey tosuccess begins. Together, we're shaping the future of technology.",
        "des3": "CEF is a dynamic tech hub that empowers individuals in our community through coding programs, AI research support, and tech forums. We're here to help you learn, connect, and innovate. Join us to be part of a vibrant tech ecosystem, where your journey to success begins. Together, we're shaping the future of technology.",
        "author":"Prof John", 
        "eventDate":"2nd April 2019", 
    },
    {
        "id": 4,
        "image": blogImage,
        "title": "Beach Vacation",
        "date": "1 November 2020",
        "summary": "CEF is a dynamic tech hub that empowers individuals in ourcommunity through coding programs, AI research support, and techforums. We're here to help you learn, connect, and innovate. Join usto be part of a vibrant tech ecosystem, where your journey tosuccess begins. Together, we're shaping the future of technology.",
        "des1": "CEF is a dynamic tech hub that empowers individuals in our community through coding programs, AI research support, and tech forums. We're here to help you learn, connect, and innovate. Join us to be part of a vibrant tech ecosystem, where your journey to success begins. Together, we're shaping the future of technology.",
        "des2": "CEF is a dynamic tech hub that empowers individuals in our community through coding programs, AI research support, and techforums. We're here to help you learn, connect, and innovate. Join usto be part of a vibrant tech ecosystem, where your journey tosuccess begins. Together, we're shaping the future of technology.",
        "des3": "CEF is a dynamic tech hub that empowers individuals in our community through coding programs, AI research support, and tech forums. We're here to help you learn, connect, and innovate. Join us to be part of a vibrant tech ecosystem, where your journey to success begins. Together, we're shaping the future of technology.",
        "author":"Prof John", 
        "eventDate":"2nd April 2019", 
    },
    {
        "id": 5,
        "image": blogImage,
        "title": "Autumn Leaves",
        "date": "1 November 2020",
        "summary": "CEF is a dynamic tech hub that empowers individuals in ourcommunity through coding programs, AI research support, and techforums. We're here to help you learn, connect, and innovate. Join usto be part of a vibrant tech ecosystem, where your journey tosuccess begins. Together, we're shaping the future of technology.",
        "des1": "CEF is a dynamic tech hub that empowers individuals in our community through coding programs, AI research support, and tech forums. We're here to help you learn, connect, and innovate. Join us to be part of a vibrant tech ecosystem, where your journey to success begins. Together, we're shaping the future of technology.",
        "des2": "CEF is a dynamic tech hub that empowers individuals in our community through coding programs, AI research support, and techforums. We're here to help you learn, connect, and innovate. Join usto be part of a vibrant tech ecosystem, where your journey tosuccess begins. Together, we're shaping the future of technology.",
        "des3": "CEF is a dynamic tech hub that empowers individuals in our community through coding programs, AI research support, and tech forums. We're here to help you learn, connect, and innovate. Join us to be part of a vibrant tech ecosystem, where your journey to success begins. Together, we're shaping the future of technology.",
        "author":"Prof John", 
        "eventDate":"2nd April 2019", 
    },
    {
        "id": 6,
        "image": blogImage,
        "title": "Wildlife Safari",
        "date": "1 November 2020",
         "summary": "CEF is a dynamic tech hub that empowers individuals in ourcommunity through coding programs, AI research support, and techforums. We're here to help you learn, connect, and innovate. Join usto be part of a vibrant tech ecosystem, where your journey tosuccess begins. Together, we're shaping the future of technology.",
        "des1": "CEF is a dynamic tech hub that empowers individuals in our community through coding programs, AI research support, and tech forums. We're here to help you learn, connect, and innovate. Join us to be part of a vibrant tech ecosystem, where your journey to success begins. Together, we're shaping the future of technology.",
        "des2": "CEF is a dynamic tech hub that empowers individuals in our community through coding programs, AI research support, and techforums. We're here to help you learn, connect, and innovate. Join usto be part of a vibrant tech ecosystem, where your journey tosuccess begins. Together, we're shaping the future of technology.",
        "des3": "CEF is a dynamic tech hub that empowers individuals in our community through coding programs, AI research support, and tech forums. We're here to help you learn, connect, and innovate. Join us to be part of a vibrant tech ecosystem, where your journey to success begins. Together, we're shaping the future of technology.",
        "author":"Prof John", 
        "eventDate":"2nd April 2019", 
    },
    {
        "id": 7,
        "image": blogImage,
        "title": "Historic Landmark",
        "date": "1 November 2020",
         "summary": "CEF is a dynamic tech hub that empowers individuals in ourcommunity through coding programs, AI research support, and techforums. We're here to help you learn, connect, and innovate. Join usto be part of a vibrant tech ecosystem, where your journey tosuccess begins. Together, we're shaping the future of technology.",
        "des1": "CEF is a dynamic tech hub that empowers individuals in our community through coding programs, AI research support, and tech forums. We're here to help you learn, connect, and innovate. Join us to be part of a vibrant tech ecosystem, where your journey to success begins. Together, we're shaping the future of technology.",
        "des2": "CEF is a dynamic tech hub that empowers individuals in our community through coding programs, AI research support, and techforums. We're here to help you learn, connect, and innovate. Join usto be part of a vibrant tech ecosystem, where your journey tosuccess begins. Together, we're shaping the future of technology.",
        "des3": "CEF is a dynamic tech hub that empowers individuals in our community through coding programs, AI research support, and tech forums. We're here to help you learn, connect, and innovate. Join us to be part of a vibrant tech ecosystem, where your journey to success begins. Together, we're shaping the future of technology.",
        "author":"Prof John", 
        "eventDate":"2nd April 2019", 
    },
    {
        "id": 8,
        "image": blogImage,
        "title": "Countryside Farm",
        "date": "1 November 2020",
         "summary": "CEF is a dynamic tech hub that empowers individuals in ourcommunity through coding programs, AI research support, and techforums. We're here to help you learn, connect, and innovate. Join usto be part of a vibrant tech ecosystem, where your journey tosuccess begins. Together, we're shaping the future of technology.",
        "des1": "CEF is a dynamic tech hub that empowers individuals in our community through coding programs, AI research support, and tech forums. We're here to help you learn, connect, and innovate. Join us to be part of a vibrant tech ecosystem, where your journey to success begins. Together, we're shaping the future of technology.",
        "des2": "CEF is a dynamic tech hub that empowers individuals in our community through coding programs, AI research support, and techforums. We're here to help you learn, connect, and innovate. Join usto be part of a vibrant tech ecosystem, where your journey tosuccess begins. Together, we're shaping the future of technology.",
        "des3": "CEF is a dynamic tech hub that empowers individuals in our community through coding programs, AI research support, and tech forums. We're here to help you learn, connect, and innovate. Join us to be part of a vibrant tech ecosystem, where your journey to success begins. Together, we're shaping the future of technology.",
        "author":"Prof John", 
        "eventDate":"2nd April 2019", 
    },
    {
        "id": 9,
        "image": blogImage,
        "title": "Urban Exploration",
        "date": "1 November 2020",
         "summary": "CEF is a dynamic tech hub that empowers individuals in ourcommunity through coding programs, AI research support, and techforums. We're here to help you learn, connect, and innovate. Join usto be part of a vibrant tech ecosystem, where your journey tosuccess begins. Together, we're shaping the future of technology.",
        "des1": "CEF is a dynamic tech hub that empowers individuals in our community through coding programs, AI research support, and tech forums. We're here to help you learn, connect, and innovate. Join us to be part of a vibrant tech ecosystem, where your journey to success begins. Together, we're shaping the future of technology.",
        "des2": "CEF is a dynamic tech hub that empowers individuals in our community through coding programs, AI research support, and techforums. We're here to help you learn, connect, and innovate. Join usto be part of a vibrant tech ecosystem, where your journey tosuccess begins. Together, we're shaping the future of technology.",
        "des3": "CEF is a dynamic tech hub that empowers individuals in our community through coding programs, AI research support, and tech forums. We're here to help you learn, connect, and innovate. Join us to be part of a vibrant tech ecosystem, where your journey to success begins. Together, we're shaping the future of technology.",
        "author":"Prof John", 
        "eventDate":"2nd April 2019", 
    },
    {
        "id": 10,
        "image": blogImage,
        "title": "Winter Wonderland",
        "date": "1 November 2020",
         "summary": "CEF is a dynamic tech hub that empowers individuals in ourcommunity through coding programs, AI research support, and techforums. We're here to help you learn, connect, and innovate. Join usto be part of a vibrant tech ecosystem, where your journey tosuccess begins. Together, we're shaping the future of technology.",
        "des1": "CEF is a dynamic tech hub that empowers individuals in our community through coding programs, AI research support, and tech forums. We're here to help you learn, connect, and innovate. Join us to be part of a vibrant tech ecosystem, where your journey to success begins. Together, we're shaping the future of technology.",
        "des2": "CEF is a dynamic tech hub that empowers individuals in our community through coding programs, AI research support, and techforums. We're here to help you learn, connect, and innovate. Join usto be part of a vibrant tech ecosystem, where your journey tosuccess begins. Together, we're shaping the future of technology.",
        "des3": "CEF is a dynamic tech hub that empowers individuals in our community through coding programs, AI research support, and tech forums. We're here to help you learn, connect, and innovate. Join us to be part of a vibrant tech ecosystem, where your journey to success begins. Together, we're shaping the future of technology.",
        "author":"Prof John", 
        "eventDate":"2nd April 2019", 
    }
]